In [ ]:
import pandas as pd
data = {
    "roll No":[1,2,3,4,5],
    "Name":["abc","qwe","dfg","jkl","opk"],
    "percentage":[75,67,89,90,67]
}
df = pd.DataFrame(data)
print(df)

   roll No Name  percentage
0        1  abc          75
1        2  qwe          67
2        3  dfg          89
3        4  jkl          90
4        5  opk          67

In [ ]:
import numpy as np
import pandas as pd
number_1 = np.random.randint(10,size= 10)
number_2 = np.random.randint(10,size=10)
year = np.arange(2000,2010)
Name = ['a','b','c','d','e','f','g','h','i','j']
data ={ "Name":Name,"Year":year,"N1":number_1,"N2":number_2}
df = pd.DataFrame(data)
print(df)

  Name  Year  N1  N2
0    a  2000   5   0
1    b  2001   1   6
2    c  2002   2   1
3    d  2003   8   9
4    e  2004   4   7
5    f  2005   0   5
6    g  2006   2   8
7    h  2007   9   8
8    i  2008   2   4
9    j  2009   7   7

In [4]:
import numpy as np
import pandas as pd
titanic= pd.read_csv("titanic.csv")
titanic

    Survived  Class  Gender   Age  SipSp  ParCh      Fare Emb Deck
0          0      3    male  22.0      1      0     $7.25   S  NaN
1          1      1  female  38.0      1      0  $71.2833   C    C
2          1      3  female  26.0      0      0    $7.925   S  NaN
3          1      1  female  35.0      1      0     $53.1   S    C
4          0      3    male  35.0      0      0     $8.05   S  NaN
..       ...    ...     ...   ...    ...    ...       ...  ..  ...
889        1      1    male  26.0      0      0     $30.0   C    C
890        0      3    male  32.0      0      0     $7.75   Q  NaN
891        0      2    male  24.0      0      0     $10.5   S  NaN
892        0      3    male  34.0      1      1     $14.4   S  NaN
893        0      3    male  36.0      0      0   $7.8958   S  NaN

[894 rows x 9 columns]

In [5]:
titanic.shape

(894, 9)

# head,tail,info,describe,iloc,loc

In [6]:
titanic.head()

  Survived  Class  Gender   Age  SipSp  ParCh      Fare Emb Deck
0        0      3    male  22.0      1      0     $7.25   S  NaN
1        1      1  female  38.0      1      0  $71.2833   C    C
2        1      3  female  26.0      0      0    $7.925   S  NaN
3        1      1  female  35.0      1      0     $53.1   S    C
4        0      3    male  35.0      0      0     $8.05   S  NaN

In [7]:
titanic.head(10)

  Survived  Class  Gender           Age  SipSp  ParCh      Fare Emb Deck
0        0      3    male          22.0      1      0     $7.25   S  NaN
1        1      1  female          38.0      1      0  $71.2833   C    C
2        1      3  female          26.0      0      0    $7.925   S  NaN
3        1      1  female          35.0      1      0     $53.1   S    C
4        0      3    male          35.0      0      0     $8.05   S  NaN
5        0      3    male  Missing Data      0      0   $8.4583   Q  NaN
6        0      1    male          54.0      0      0  $51.8625   S    E
7        0      3    male           2.0      3      1   $21.075   S  NaN
8        1      3  female          27.0      0      2  $11.1333   S  NaN
9        1      2  female          14.0      1      0  $30.0708   C  NaN

In [9]:
titanic.tail(-10)

    Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
10         1      3  female   4.0      1      1    $16.7   S    G
11         1      1  female  58.0      0      0   $26.55   S    C
12         0      3    male  20.0      0      0    $8.05   S  NaN
13         0      3    male  39.0      1      5  $31.275   S  NaN
14         0      3  female  14.0      0      0  $7.8542   S  NaN
..       ...    ...     ...   ...    ...    ...      ...  ..  ...
889        1      1    male  26.0      0      0    $30.0   C    C
890        0      3    male  32.0      0      0    $7.75   Q  NaN
891        0      2    male  24.0      0      0    $10.5   S  NaN
892        0      3    male  34.0      1      1    $14.4   S  NaN
893        0      3    male  36.0      0      0  $7.8958   S  NaN

[884 rows x 9 columns]

In [10]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 894 entries, 0 to 893
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  894 non-null    object
 1   Class     894 non-null    int64
 2   Gender    894 non-null    object
 3   Age       758 non-null    object
 4   SipSp     894 non-null    int64
 5   ParCh     894 non-null    int64
 6   Fare      894 non-null    object
 7   Emb       892 non-null    object
 8   Deck      203 non-null    object
dtypes: int64(3), object(6)
memory usage: 63.0+ KB

In [8]:
titanic.describe()

            Class       SipSp       ParCh
count  894.000000  894.000000  894.000000
mean     2.309843    0.522371    0.381432
std      0.835370    1.101283    0.805171
min      1.000000    0.000000    0.000000
25%      2.000000    0.000000    0.000000
50%      3.000000    0.000000    0.000000
75%      3.000000    1.000000    0.000000
max      3.000000    8.000000    6.000000

In [11]:
summer = pd.read_csv("summer.csv")
summer

,Year,City,Sport,Discipline,Athlete Name,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold Medal
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"Malokinis, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold Medal
4,1896,Athens,Aquatics,Swimming,"Chasapis, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31165,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31166,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31167,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31168,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31169,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [29]:
import pandas as pd
summer = pd.read_csv("summer.csv",index_col= "Athlete Name")
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete Name,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold Medal
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"Malokinis, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold Medal
"Chasapis, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [30]:
summer["Sport"]

Athlete Name
 HAJOS, Alfred                  Aquatics
 HERSCHMANN, Otto               Aquatics
 DRIVAS, Dimitrios              Aquatics
 Malokinis, Ioannis             Aquatics
 Chasapis, Spiridon             Aquatics
                                 ...
 JANIKOWSKI, Damian            Wrestling
 REZAEI, Ghasem Gholamreza     Wrestling
 TOTROV, Rustam                Wrestling
 ALEKSANYAN, Artur             Wrestling
 LIDBERG, Jimmy                Wrestling
Name: Sport, Length: 31170, dtype: object

In [31]:
summer[["Sport","City"]]

                                 Sport    City
Athlete Name
 HAJOS, Alfred                Aquatics  Athens
 HERSCHMANN, Otto             Aquatics  Athens
 DRIVAS, Dimitrios            Aquatics  Athens
 Malokinis, Ioannis           Aquatics  Athens
 Chasapis, Spiridon           Aquatics  Athens
...                                ...     ...
 JANIKOWSKI, Damian          Wrestling  London
 REZAEI, Ghasem Gholamreza   Wrestling  London
 TOTROV, Rustam              Wrestling  London
 ALEKSANYAN, Artur           Wrestling  London
 LIDBERG, Jimmy              Wrestling  London

[31170 rows x 2 columns]

In [16]:
summer.iloc[0]

Year                       1896
City                     Athens
Sport                  Aquatics
Discipline             Swimming
Athlete Name     HAJOS, Alfred
Country                     HUN
Gender                      Men
Event            100M Freestyle
Medal                Gold Medal
Name: 0, dtype: object

In [28]:
summer.iloc[[1,2,3]]

AttributeError: ignored

In [ ]:
summer.iloc[1:4]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold

In [ ]:
summer.iloc[-5:-1]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze

In [ ]:
summer.iloc[:]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [ ]:
summer.iloc[[2,45,78]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"PERSAKIS, Ioannis",1896,Athens,Athletics,Athletics,GRE,Men,Triple Jump,Bronze
"PERSAKIS, Petros",1896,Athens,Gymnastics,Artistic G.,GRE,Men,Rings,Bronze

In [ ]:
summer.iloc[0,:3]

Year         1896
City       Athens
Sport    Aquatics
Name: HAJOS, Alfred, dtype: object

In [ ]:
summer.iloc[2,[0,2,4]]

Year           1896
Sport      Aquatics
Country         GRE
Name: DRIVAS, Dimitrios, dtype: object

In [ ]:
summer.iloc[34:39,[1,5,7]]

                        City Gender   Medal
Athlete
GARRETT, Robert       Athens    Men  Silver
KELLNER, Gyula        Athens    Men  Bronze
LOUIS, Spyridon       Athens    Men    Gold
VASILAKOS, Kharilaos  Athens    Men  Silver
DAMASKOS, Evangelos   Athens    Men  Bronze

In [ ]:
summer.loc["CHASAPIS, Spiridon","Country"]

'GRE'

In [ ]:
summer.loc[:"CHASAPIS, Spiridon",["City","Sport","Discipline"]]

                      City     Sport Discipline
Athlete
HAJOS, Alfred       Athens  Aquatics   Swimming
HERSCHMANN, Otto    Athens  Aquatics   Swimming
DRIVAS, Dimitrios   Athens  Aquatics   Swimming
MALOKINIS, Ioannis  Athens  Aquatics   Swimming
CHASAPIS, Spiridon  Athens  Aquatics   Swimming